### ISSUE TITLE
怎么正确配置访问接口正常使用功能？

### ISSUE THREAD

**Issue by inzaghihao** [yeliudev/LemonJournal#1]

**Comment by yeliudev** [comment]
1. 准备好自己的 AppId 和 AppSecret（可在微信公众平台注册后获取）
2. 在 `project.config.json` 的 `appid` 字段中填入 AppId
3. 在 `/client/utils/util.js` 中相应位置填入 AppId 和 AppSecret
4. 在微信开发者工具中重新导入整个项目，编译运行即可

**Comment by cherishloveyou** [comment]
仅配置了小程序的AppId 和 AppSecret 登录提示 skey不存在 还要自己配置后台嘛？

**Comment by yeliudev** [comment]
不用配置后台，清除所有缓存后打开调试模式即可

**Comment by liuqk3** [comment]
现在后台配置还有效吗？为什么我设置了AppID和AppSeceret还是不行呢？
